on:
  push:
    tags:
      - v*

jobs:
  luarocks_pack:
    name: pack-luarocks
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: "3.11.0"
    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName
      with:
        tagRegex: "^v(.*)$"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    # Install some package
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
    #   with:
    #     ## If no one connects after 5 minutes, shut down server.
    #     wait-timeout-minutes: 5
    #   #   ## limits ssh access and adds the ssh public key for the user which triggered the workflow
    #   #   limit-access-to-actor: true
    #   #   ## limits ssh access and adds the ssh public keys of the listed GitHub users
    #   #   limit-access-to-users: laoshancun@macos,laoshancun
    - name: update rockspec
      run: |
        sed -i -E "s/version *= *.*/version = \"${GIT_TAG_NAME}\"/g;s|tag *= *.*(,?)|tag = \"${GITHUB_REF##*/}\"\1|g" lua-aho-corasick.rockspec
        mv lua-aho-corasick.rockspec lua-aho-corasick-${GIT_TAG_NAME}.rockspec
    - name: test install module
      run: luarocks make
    # - name: luarocks pack
    #   run: luarocks pack lua-aho-corasick-${GIT_TAG_NAME}.rockspec
    - name: upload 
      run: luarocks upload lua-aho-corasick-${GIT_TAG_NAME}.rockspec --api-key=${{ secrets.LUA_ROCKS_API_KEY }}

